MVC/MVC/Controllers/ExperienceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;
using MVC;

namespace Kevin.MVCSite.Controllers
{
    public class ExperienceController : BaseController
    {
        public ActionResult Experience()
        {
            ViewBag.Title = "Kevin Cornelison Work Experience";
            return View();
        }
        public ActionResult RainmakerMembershipSystems()
        {
            ViewBag.Title = "Rainmaker Membership Systems";
            return View();
        }
        public ActionResult MVTransportation()
        {
            ViewBag.Title = "MV Transit";
            return View();
        }
        public ActionResult GSCS()
        {
            ViewBag.Title = "GSCS";
            return View();
        }
        public ActionResult HeritageAuctionGalleries()
        {
            ViewBag.Title = "Heritage Auction Galleries";
            return View();
        }
        public ActionResult TarrantBusinessSystems()
        {
            ViewBag.Title = "Tarrant Business Systems";
            return View();
        }
        public ActionResult FeaturedSkills()
        {
            ViewBag.Title = "Featured Skills";
            return View();
        }
        public ActionResult FullStackDeveloper()
        {
            ViewBag.Title = "Full Stack Developer";
            return View();
        }
    }
}

MVC/MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC;


namespace Kevin.MVCSite.Controllers
{
    public class HomeController : BaseController
    {

        public ActionResult Index()
        {
            ViewBag.Title = "Kevin Cornelison";
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Title = "About Kevin";
            ViewBag.Message = "MVC online portfolio for Kevin Cornelison.";
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Kevin Cornelison";

            return View();
        }
        public ActionResult MVC()
        {
            return View();
        }


    }
}

MVC/MVC/Views/Home/About.cshtml
<h2>@ViewBag.Title.</h2>

<dl class="dl-horizontal">
    <dt>March 18th, 1967</dt>
    <dd>
        Born and raised here in Fort Worth.
    </dd>
    <dt></dt>
    <dd><hr /></dd>
    <dt>1973</dt>
    <dd>
        I went to O.H. Stowe Elementary, North Oaks Junior High and Haltom High School in Haltom City, TX.
        I played trombone starting in 6th grade.
    </dd>
    <dt></dt>
    <dd><hr /></dd>
    <dt>1980 - 1984</dt>
    <dd>
        As a teenager, I took many electrical things apart and rarely put them back together.
        <br/>
        When anything would break, I would immediately take it apart.  I figured, it was already
        broken.  I can't make it any worse.
        
    </dd>
    <dt></dt>
    <dd><hr /></dd>
    <dt>1985</dt>
    <dd>
        I got my first computer job in Virginia Beach, VA at around the age of 18.  I worked at the local Commodore 64 store.  
        I fixed printers, Commodore 64s, anything  electronic.  And by fixed, I mean I would trouble shoot the problem
        down to the chip, then pull and replace the bad chip.
    </dd>
    <dt></dt>
    <dd><hr /></dd>
    <dt>1986</dt>
    <dd>
        At the age of 19, I moved back to the Fort Worth Area. I fixed Commodore 64s out of my house.
        I diagnosed board problems and pulled/replaced chips.
    </dd>
    <dt></dt><dd><hr /></dd>
    <dt>1989 - 1996</dt>
    <dd>
        My first REAL tech job was working on Copiers.  I worked on all makes, all models, all sizes.  
    </dd>
    <dt></dt><dd><hr /></dd>
    <dt>1996-2009</dt>
    <dd>
        In 1996, I applied for a job at @Html.ActionLink("Heritage Auction Galleries", "HeritageAuctionGalleries", "Experience") as a Help Desk tech.  There were about 40 employees at the time.  I was responsible
        for anything that plugged into the wall.  Including printer, computers, servers, etc.
    </dd>
    <dt></dt>    
    <dd>
        When I started at @Html.ActionLink("Heritage Auction Galleries", "HeritageAuctionGalleries", "Experience"), I told them that I have been programming computers since I was a teen and I would like to write
        code someday.  They said if the opportunity came up, they would be ok with that.
    </dd>
    <dt></dt>
    <dd>
        Over the years at @Html.ActionLink("Heritage Auction Galleries", "HeritageAuctionGalleries", "Experience"), I started to develop and program an imaging system for processing images to the website.
        Around 2005, I started programming full time at @Html.ActionLink("Heritage Auction Galleries", "HeritageAuctionGalleries", "Experience").
    </dd>
    <dt></dt>
    <dd><hr /></dd>
    <dt>2009 - 2016</dt>
    <dd>
        There is a gap in my Resume because I became deathly sick and was unable to work or even take care of my self.
        After I had my medical issues resolved, I went back to work in 2015.
    </dd>
    <dt></dt>
    <dd><hr /></dd>
    <dt>July 2015 - Feb 2017</dt>
    <dd>
        I started working at @Html.ActionLink("Rainmaker Membership Systems", "RainmakerMembershipSystems", "Experience") 
        in July of 2015.  I spent the last year and a half learning
        all the new technologies that had come out while I was sick.  @Html.ActionLink("You can view them here", "FeaturedSkills", "Experience").
    </dd>
    <dt></dt>
    <dd><hr /></dd>
    <dt>The Next Chapter.</dt>
    <dd>
        I am currently looking for that good fit professionally.  
        <br/>After looking at my @Html.ActionLink("Skillset", "FeaturedSkills", "Experience"), 
        if you know of a position that would be a good fit, please contact me below.
        <h4>Some things to know.</h4>
        <ul>
            <li>I am a US Citizen</li>
            <li>I am looking for Full Time work, but would listen to any opportunity to see if it is a good fit.</li>
            <li>I am looking to stay in the DFW Metroplex, so I will not relocation</li>
        </ul>
    </dd>
</dl>


<h3>There are several ways to contact me:</h3>
<dl class="dl-horizontal">
    <dt>Name</dt><dd>Kevin Cornelison</dd>
    <dt>Location</dt><dd>Fort Worth, TX 76120</dd>
    <dt>Phone</dt><dd>817.ASK.ME</dd>
    <dt>Email:</dt><dd><a href="mailto:KevinAppDev@gmail.com">
                           <img width="50" src="~/Content/Images/gmail-icon-50003.png" />KevinAppDev@gmail.com</a></dd>
    <dt>LinkedIn</dt><dd><a target="_blank" href="https://www.linkedin.com/in/kevinappdev/" class=""><img height="50" src="~/Content/Images/linkedin_link.png" /></a></dd>
    <dt>FaceBook</dt><dd><a target="_blank" href="https://www.facebook.com/kevin.cornelison.5" class=""><img height="45" src="~/Content/Images/facebook_icon.png" /></a></dd>
</dl>

MVC/MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

You can contact me on Linked IN or Facebook. or email below

<address>
    Fort Worth, TX 76120<br />
    <abbr title="Phone">P:</abbr>
    817.937.ASKME
</address>

<address>
    <strong>Request INFO:</strong>   <a href="mailto:KevinAppDev@gmail.com">KevinAppDev@gmail.com</a><br />
</address>

MVC/MVC/Views/Home/Index.cshtml
<div class="container row">
    @*Profile*@
    <div class="" id="profile">
        @Html.Partial("_KevinAboutPartial")
        <H2>A little history.</H2>
        <p>
            I was born in 1967.  I always had an inherent understanding of all things mechanical and electrical.
            Thru my teenage years, I took a lot of things apart, but rarely put them back to gether.
        </p>
        <p>
            At around 14, I got the Atari 2600.  I was frustrated with the stick controllers.
            After a while, they would stick or just quit working.  I got ahold of an old adding machine.  Pulled
            the keyboard out.  Attached the broken joystick wire to the buttons and I played Asteroids on my Atari
            2600 just like at the arcade.
        </p>
        <p >
            At 15, I got my first Commodore 64.  In the back was a programmer's guide. <abbr title="BASIC">Beginners All-Purpose Symbolic Instruction Code.</abbr> 
            I have been a programmer ever since.
        </p>
        <h2>What about now.</h2>
        <p>
            I am a  @Html.ActionLink("Full Stack Developer", "FullStackDeveloper", "Experience",null, new { @title = "What is a Full Stack Developer?" })</>.
        </p>
        <p>
            I am comfortable working in many technologies.
        </p>
        <p>
            My job experience has dictated what technologies I am proficient in and
            which technologies I have a basic knowledge of and which technologies I
            am aware of but have not written code in.
        </p>
        <p>
            Please click <span>@Html.ActionLink("Featured Skills", "FeaturedSkills", "Experience",null, new { @title = "Featured skillset and relevent experience." })</span> to view a detailed list of my
            current skillset and relative experience with each.
        </p>
    </div>
</div>

MVC/MVC/Views/Home/MVC.cshtml
<h2>This site was created using Microsoft MVC</h2>
<p>
    Click <a href="http://angular.kevinappdev.com">here</a> to view the Angular JS version.
</p>